import { BarChart3, CalendarRange, Download, FileText, ShieldCheck } from "lucide-react";
import { categories, formatCurrency, transactions } from "@/lib/finance";

const reports = [{ title: "Resumen mensual", period: "Enero 2025", detail: "Ingresos, gastos y balance", icon: CalendarRange }, { title: "Hábitos de gasto", period: "Últimos 30 días", detail: "Categorías principales y evolución", icon: BarChart3 }, { title: "Informe de privacidad", period: "Estado actual", detail: "Datos almacenados localmente", icon: ShieldCheck }];

export default function InformesPage() {
  const total = transactions.filter((item) => item.type === "expense").reduce((sum, item) => sum + item.amount, 0);
  return <div className="space-y-8"><section><p className="mb-2 text-sm font-semibold text-moss">Lecturas para decidir mejor</p><h1 className="text-3xl font-bold tracking-tight lg:text-4xl">Informes</h1><p className="mt-2 text-slate-500">Convierte tus movimientos en una visión clara de tus hábitos.</p></section><section className="grid gap-4 md:grid-cols-3">{reports.map(({ title, period, detail, icon: Icon }) => <article key={title} className="rounded-2xl border border-[#e0e7df] bg-white p-5 shadow-soft"><span className="grid h-10 w-10 place-items-center rounded-xl bg-mint text-moss"><Icon size={20} /></span><h2 className="mt-5 font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{period}</p><p className="mt-4 text-sm text-slate-600">{detail}</p><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border border-[#bfd4c4] px-3 py-2.5 text-sm font-bold text-moss hover:bg-[#f1f8f2]"><Download size={16} />Descargar PDF</button></article>)}</section><section className="grid gap-5 lg:grid-cols-[1fr_1.2fr]"><div className="grid-paper rounded-2xl border border-[#d8e4d9] p-6"><div className="flex items-center gap-3"><FileText className="text-moss" /><div><h2 className="font-bold">Vista previa · Enero 2025</h2><p className="text-sm text-slate-500">Resumen listo para exportar</p></div></div><div className="mt-8 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/80 p-4"><p className="text-xs text-slate-500">Gastos totales</p><b className="mt-2 block text-xl">{formatCurrency(total)}</b></div><div className="rounded-xl bg-white/80 p-4"><p className="text-xs text-slate-500">Ahorro estimado</p><b className="mt-2 block text-xl text-emerald-700">37%</b></div></div><div className="mt-4 rounded-xl bg-moss p-4 text-white"><p className="text-xs text-white/70">Lectura principal</p><p className="mt-2 text-sm font-semibold">Restaurantes y comida concentra la mayor oportunidad de ahorro este mes.</p></div></div><div className="rounded-2xl border border-[#e0e7df] bg-white p-6 shadow-soft"><h2 className="font-bold">Categorías principales</h2><p className="mt-1 text-sm text-slate-500">Gasto acumulado en el periodo</p><div className="mt-6 space-y-5">{categories.slice(0, 5).map((category, index) => <div key={category.id}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{category.name}</span><span className="text-slate-500">{["42%", "28%", "14%", "9%", "7%"][index]}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{ width: ["42%", "28%", "14%", "9%", "7%"][index], backgroundColor: category.color }} /></div></div>)}</div></div></section></div>;
}
